use_frameworks!

platform :ios, '9.0'

target 'Hana_Example' do
  pod 'Hana', :path => '../'

  target 'Hana_Tests' do
    inherit! :search_paths

    pod 'Quick'
    pod 'Nimble'
    pod 'FBSnapshotTestCase'
    pod 'Nimble-Snapshots'
  end
end
