use_frameworks!

platform :ios, '10.0'

target 'Hana_Example' do
  pod 'Hana', :path => '../'

  target 'Hana_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 4.0.0'
    pod 'Nimble', '~> 9.2.1'
    pod 'FBSnapshotTestCase', '~> 2.1.4'
    pod 'Nimble-Snapshots', '~> 9.1.1'
  end
end
